export default function TermsPage() {
  const lastUpdated = '12 May 2026'

  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-10">Last updated: {lastUpdated} · Version 1.0</p>

      <section className="space-y-8 text-sm leading-relaxed text-foreground">

        <div>
          <h2 className="text-lg font-semibold mb-2">1. The service</h2>
          <p>
            Jobba is an AI-powered job search assistant. It fetches job vacancies from third-party job boards,
            scores them against your profile using artificial intelligence, and helps you generate cover letters
            and tailored resumes. By creating an account, you agree to these terms.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">2. Your account</h2>
          <ul className="list-disc ml-5 space-y-1">
            <li>You must be at least 16 years old to use Jobba</li>
            <li>You are responsible for keeping your account credentials secure</li>
            <li>You may only create one account per person</li>
            <li>You may delete your account at any time from Settings</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">3. Your data and content</h2>
          <p>
            You retain ownership of your resume and any content you upload. By uploading your resume,
            you grant Jobba a limited licence to process it using AI (Claude by Anthropic) solely to
            provide the service. We do not sell your data or share it with employers.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">4. AI-generated content</h2>
          <p>
            Cover letters and resume suggestions are generated by artificial intelligence.
            You are responsible for reviewing all AI-generated content before using it.
            Always verify that a generated cover letter accurately represents your experience
            before submitting it to an employer.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">5. Job listings</h2>
          <p>
            Vacancies are sourced from Adzuna, Nationale Vacaturebank, and Intermediair.
            Jobba does not verify the accuracy or availability of listings. Always verify
            a vacancy directly on the employer&apos;s website before applying.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">6. Acceptable use</h2>
          <p>You agree not to create fake profiles, scrape the service, upload illegal content, or share your account.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">7. Free service and credits</h2>
          <p>
            Jobba is currently free. New users receive a limited number of AI generation credits.
            Daily job matching is always free. We may introduce paid plans in future — you will be notified in advance.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">8. Limitation of liability</h2>
          <p>
            Jobba is provided &quot;as is&quot; without warranty. We are not liable for employment decisions
            made based on our service or for inaccuracies in AI-generated content.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">9. Governing law</h2>
          <p>These terms are governed by Dutch law. Disputes will be submitted to the competent court in Amsterdam.</p>
        </div>

      </section>
    </main>
  )
}
