-- Migration 002: Fix broken constraints and add missing ai_unlocked column
-- Run in the Supabase SQL editor

-- C2: Add ai_unlocked column to job_matches (used by credits.ts but never in schema)
alter table public.job_matches
  add column if not exists ai_unlocked boolean default false;

-- C3: Allow 'manual' and 'jobbird' sources (import route uses 'manual'; source badge lists 'jobbird')
alter table public.jobs
  drop constraint if exists jobs_source_check;
alter table public.jobs
  add constraint jobs_source_check
  check (source in ('adzuna', 'nvb', 'intermediair', 'manual', 'jobbird'));

-- C4: Allow 'tailored' tone for cover letters generated by the tailor endpoint
alter table public.cover_letters
  drop constraint if exists cover_letters_tone_check;
alter table public.cover_letters
  add constraint cover_letters_tone_check
  check (tone in ('formal', 'warm', 'tailored'));

-- C5: Allow 'rescore' step in pipeline_logs (used by /api/scan/rescore)
alter table public.pipeline_logs
  drop constraint if exists pipeline_logs_step_check;
alter table public.pipeline_logs
  add constraint pipeline_logs_step_check
  check (step in ('fetch', 'score', 'email', 'scan_now', 'rescore'));
